### ISSUE TITLE
Bug in the testing

### ISSUE THREAD

**Issue by jamierytlewski** [practice-dev/practice-dev#2]
I'm trying to use Blazor on this and the testing doesn't seem to work.

https://practice-dev-blazor-server.azurewebsites.net/counter

I can get as far as until the click, and on the click it's saying the 1 doesn't increment when it clearly does. I'm not sure if it's the testing engine you are using or what. Love the app, can't wait to see what the issue is.

![image](https://user-images.githubusercontent.com/695710/87983508-7c7a6780-caa6-11ea-82b2-4a1333f02887.png)

**Comment by lstkz** [comment]
Hi @jamierytlewski,

I will try to debug it locally.
Is it possible that you display static HTML, but after 0.5s - 2s, you attach event handlers?

**Comment by lstkz** [comment]
I've found the issue, but I am don't know to solve it.
Blazor uses prerendering and sends the HTML. It takes ~1s to initialize the frontend app, all handlers, etc., but the tester starts clicking and checking all interactions before that.
The solution would be to disable the pre-rendering, or not displaying HTML if it's not ready, but I don't know how to do this.
I will try to find someone familiar with blazor.

Here is a similar issue with Blazzor, but using Cypress https://github.com/cypress-io/cypress/issues/4635

**Comment by chrissainty** [comment]
Wouldn't the better option be to put a delay in the test to wait for the app to become interactive? That way the test will have more value as if that doesn't happen, the tests will fail and show a possible issue. By removing prerendering, something that I assume would be wanted in "live", you're not testing the app in the same state as it would be in production.

**Comment by lstkz** [comment]
Thanks @chrissainty for joining 🙂
Is it possible to detect if the app is interactive? Adding a random timeout 1-2s, can solve the problem, but in most cases, it will slow time the testing processes for other frameworks. Also, there is a risk that tests will be flaky, and I am trying to avoid that.

The simplest workaround would be to hide the HTML (by css `display: none`), if the app is not interactive only for testing purposes. Is it possible?

**Comment by egil** [comment]
I humbly suggest looking at bUnit (https://bunit.egilhansen.com) for testing Blazor components. It's only when you lots of JavaScript that as part of your components that end-2-end testing makes sense.

With bUnit, the counter component is tested entirely in C# in milliseconds, like so:

```c#
[Fact] 
public void CounterShouldIncrementWhenClicked() 
{ 
  // Arrange: render the Counter.razor component 
  var cut = RenderComponent<Counter>(); 

  // Act: find and click the <button> element to increment 
  // the counter in the <p> element
  cut.Find("button").Click(); 

  // Assert: first find the <p> element, then verify its content
  cut.Find("p").MarkupMatches("<p>Current count: 1</p>"); 
}
```

**Comment by egil** [comment]
Ahh I see. I'll go back in my corner then 🙂

**Comment by jamierytlewski** [comment]
Just as another issue when you talked about pre-rendering. Blazor does both server and WASM. I've tried both and server version (which is the site above) and the WASM version. The WASM version does a lot of pre-rendering and I can see why it won't work with the testing (https://practice-dev-blazor.azurewebsites.net/counter), what I'm not understanding is that it's 1 

1. Recognizing the elements. 
1. Getting the default value of 0.

Then it's breaking. I noticed you are using your own version of a testing suite on top of puppeteer, do you think that might be causing it? Just throwing that out there.

**Comment by chrissainty** [comment]
@jamierytlewski The elements are recognised because the prerendering generated them, they're just not interactive yet. It's the same reason it can get the initial value as that was generated by the prerendering as well. It fails when it checks for 1 as the button isn't interactive yet, hence the counter doesn't increment.

**Comment by lstkz** [comment]
@jamierytlewski I was able to figure it out.
It works if you change
```
<component type="typeof(App)" render-mode="ServerPrerendered" />
```
to
```
<component type="typeof(App)" render-mode="Server" />
```

in `Pages/_Host.cshtml`

**Comment by jamierytlewski** [comment]
Thansk @lstkz . I was looking at that as well as people talked about. Now the question and maybe @chrissainty can point to some good discussions, but if `ServerPrerendered` is the default, why would I choose `Server` now and what are some drawbacks. Thanks! It's all working now.

**Comment by lstkz** [comment]
There are some benefits of pre-rendering or SSR (server-side rending):
- better SEO,
- no extra API requests on page load because they are loaded on the server-side,
- the user can see the page faster (by a few ms).

However, when solving challenges at https://practice.dev, the above things are not the issue 🙂.
I will check if other SSR frameworks have the same issues, and add proper notes.

**Comment by chrissainty** [comment]
@jamierytlewski `Static` only renders static HTML. It's there for apps which want to render some dynamically generated content on the server that doesn't need to be updated after that initial render. That's why it fails the test, as it will never be made interactive.

**Comment by jamierytlewski** [comment]
Thanks for all the help. I'm going to close as it's all working with changing the render-mode. This is a great site. Keep up the good work.
