### ISSUE TITLE
Site preview shows nothing and breaks when trying to access anything

### ISSUE THREAD

**Issue by jichanbachan** [practice-dev/practice-dev#27]
I seem to be getting a blank page for the preview, even for valid and working code.

![image](https://user-images.githubusercontent.com/40665601/132117466-6b7110a0-5de5-40ea-a676-bc8acaf6f577.png)

Writing anything into the URL bar breaks it permanently (at least until I reload the entire practive-dev page).

![image](https://user-images.githubusercontent.com/40665601/132117563-193a8ee3-84a3-431e-8d1f-777b284c83bc.png)

Apologies if I'm simply missing something obvious.

**Comment by lstkz** [comment]
What browser do you use? Unfortunately, it doesn't work in Firefox and Safari :/
I will fix it, but I will need some time.

**Comment by jichanbachan** [comment]
Ah, I use Firefox.  I'll use a different browser in the meantime.  Thank you

**Comment by lstkz** [comment]
@jichanbachan fixed. It should work on Firefox now :)
