### ISSUE TITLE
Counter challenge: solution not recognised or run

### ISSUE THREAD

**Issue by lucitemple** [practice-dev/practice-dev#36]
Hi, 
RE: ['Counter' challenge ](https://practice.dev/module/react-practice/challenge/counter)

- Code solution doesn't appear to have any impact on the preview in the right hand pane. Even changing the HTML to say something other than a Count : 0 doesn't change anything.
- Only first three tests will pass.
- Even copying & running a "successful" solution doesn't pass all the tests. So this isn't an issue with my coded solution.
<img width="1344" alt="Screen Shot 2022-01-31 at 11 47 52 am" src="https://user-images.githubusercontent.com/5368666/151725365-077e3f39-c31f-4b21-b7f3-ae73dee947c8.png">

<img width="888" alt="Screen Shot 2022-01-31 at 11 52 56 am" src="https://user-images.githubusercontent.com/5368666/151725459-ab79b234-bc51-4f6a-a526-3dc55877de35.png">

**Comment by lstkz** [comment]
Hi @lucitemple 
I can see that the file is not saved. You must press ctrl+s 😉
